# This file was generated by GoReleaser. DO NOT EDIT.
cask "ota" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "74342b48bd9454e80a62795f77b24c5c0b0a17dee2f4e70537ea3fea930f19d4"
      url "https://github.com/tedilabs/ota/releases/download/v#{version}/ota_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "3033f993f9e5f12bce591d73d6c44d58c24df08cd35a56784698557ea0125a84"
      url "https://github.com/tedilabs/ota/releases/download/v#{version}/ota_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42f2dd1e27d8dfab681b1b18ac87d6eec74c5a962a736e76b7aad567b95c98c8"
      url "https://github.com/tedilabs/ota/releases/download/v#{version}/ota_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee42ca4e835acfed78f4f3663c75e74ce451ff050dfb6e9e64d15a8e5ef905e5"
      url "https://github.com/tedilabs/ota/releases/download/v#{version}/ota_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ota"
  desc "A k9s-style terminal UI for Okta Workforce Identity."
  homepage "https://github.com/tedilabs/ota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ota"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ota"]
    end
  end

  # No zap stanza required

end
