# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ota < Formula
  desc "A k9s-style terminal UI for Okta Workforce Identity."
  homepage "https://github.com/tedilabs/ota"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedilabs/ota/releases/download/v0.1.2/ota_0.1.2_macos_amd64.tar.gz"
      sha256 "30f4f77a661a1096623c9944d060e2038a5a7ed313e849f20c64dd1cf2b755ef"

      define_method(:install) do
        bin.install "ota"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedilabs/ota/releases/download/v0.1.2/ota_0.1.2_macos_arm64.tar.gz"
      sha256 "5a98603492d1f1f2574020314ec2c7c27c0ac8741aa8ed39edcc8ab66b2bb5bc"

      define_method(:install) do
        bin.install "ota"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/ota/releases/download/v0.1.2/ota_0.1.2_linux_amd64.tar.gz"
      sha256 "56676ee677bfa434be8f8d8ea22daf63010a083e82f6d5ea609df2f0230878e7"
      define_method(:install) do
        bin.install "ota"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/ota/releases/download/v0.1.2/ota_0.1.2_linux_arm64.tar.gz"
      sha256 "a7f79550374e1134ab59bb0fe02dae157b7be5f3e5cd6b11b6342277fe834d29"
      define_method(:install) do
        bin.install "ota"
      end
    end
  end

  def caveats
    <<~EOS
      Configure a profile before first run — either point at your org
      with environment variables:
        export OKTA_ORG_URL=https://your-org.okta.com
        export OKTA_API_TOKEN=...

      or write ~/.config/ota/config.yaml. Then launch with:
        ota
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ota --version")
  end
end
