# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvault < Formula
  desc "Universal Terraform credentials helper with pluggable secret backends"
  homepage "https://github.com/tedilabs/tfvault"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.4.0/tfvault_0.4.0_darwin_amd64.tar.gz"
      sha256 "c0f053ac7611b4bfbf2c0fb5970e823b161613ecd18e6b11363bcb69a574e847"

      define_method(:install) do
        bin.install "tfvault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.4.0/tfvault_0.4.0_darwin_arm64.tar.gz"
      sha256 "6512de1d1b27507c997eaa05aac6e19e073d987c594de200e343ff1e2a249a70"

      define_method(:install) do
        bin.install "tfvault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.4.0/tfvault_0.4.0_linux_amd64.tar.gz"
      sha256 "64684138eb8789cc28c1e2c43cad2f3cdb4be59d3996b5c35bf9837e57c5ee71"
      define_method(:install) do
        bin.install "tfvault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.4.0/tfvault_0.4.0_linux_arm64.tar.gz"
      sha256 "9aecd65076db43cec3bb82a48ca694cf71f94345f10a5f51bfc4ead8f570f600"
      define_method(:install) do
        bin.install "tfvault"
      end
    end
  end

  def caveats
    <<~EOS
      Link the helper into Terraform's plugin directory:
        tfvault install

      Then add to your ~/.terraformrc:
        credentials_helper "tfvault" {
          args = []
        }

      Verify the setup with:
        tfvault status
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfvault version")
  end
end
