# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvault < Formula
  desc "Universal Terraform credentials helper with pluggable secret backends"
  homepage "https://github.com/tedilabs/tfvault"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.3.0/tfvault_0.3.0_darwin_amd64.tar.gz"
      sha256 "588d5445f19503d0e8e70968b1a7dd8bcbf1242b4b8c77d6abcc2774bba76c99"

      define_method(:install) do
        bin.install "tfvault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.3.0/tfvault_0.3.0_darwin_arm64.tar.gz"
      sha256 "24933cd86a57c60ffc874f4bba92742931cb879d16da467067667a29619b3852"

      define_method(:install) do
        bin.install "tfvault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.3.0/tfvault_0.3.0_linux_amd64.tar.gz"
      sha256 "c5d7021e8ec3e47dddafe90f97da61c5cbfc79cece1ee915ac9e2364bf37c380"
      define_method(:install) do
        bin.install "tfvault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.3.0/tfvault_0.3.0_linux_arm64.tar.gz"
      sha256 "9d1271cd203818ab59691bb55c6fc51a1bac8a9c931b875de60c192c8e1708c9"
      define_method(:install) do
        bin.install "tfvault"
      end
    end
  end

  def caveats
    <<~EOS
      Link the helper into Terraform's plugin directory:
        tfvault install

      Then add to your ~/.terraformrc:
        credentials_helper "tfvault" {
          args = []
        }

      Verify the setup with:
        tfvault status
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfvault version")
  end
end
