# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvault < Formula
  desc "Universal Terraform credentials helper with pluggable secret backends"
  homepage "https://github.com/tedilabs/tfvault"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.5.0/tfvault_0.5.0_darwin_amd64.tar.gz"
      sha256 "61066de7e02e2178bfcf00fe0925607e35381e5d292047c2eaa6861bdd3ee86f"

      define_method(:install) do
        bin.install "tfvault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.5.0/tfvault_0.5.0_darwin_arm64.tar.gz"
      sha256 "0e46ee2985c9c1a188abd198d4dc2e88ff17943825fa7cd8b72a57e55a9e27ab"

      define_method(:install) do
        bin.install "tfvault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.5.0/tfvault_0.5.0_linux_amd64.tar.gz"
      sha256 "1a9ffea6fd71d11662176879cdc6dd6bae04b19f301274a437d9c367f8f56978"
      define_method(:install) do
        bin.install "tfvault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedilabs/tfvault/releases/download/v0.5.0/tfvault_0.5.0_linux_arm64.tar.gz"
      sha256 "062357038c54c1028dda79833997a24d6e024e554fb4ca8072b051522a07f1e4"
      define_method(:install) do
        bin.install "tfvault"
      end
    end
  end

  def caveats
    <<~EOS
      Link the helper into Terraform's plugin directory:
        tfvault install

      Then add to your ~/.terraformrc:
        credentials_helper "tfvault" {
          args = []
        }

      Verify the setup with:
        tfvault status
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfvault version")
  end
end
